---
ID: "dffee92b-0441-45a4-9207-67810b72bd46"
Parent: "895e25c4-12b2-4b2c-8233-82f3b79eef53"
Template: "bc71d442-3e4f-46ba-887c-746e54f9bb83"
Path: /sitecore/system/Settings/Services/Rendering Hosts/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4270ae06-bd81-4e8a-898f-5e530cbb8544"
    - ID: "e32c1801-79b3-4fc1-a9c4-3c6e6c2968ae"
      Hint: ServerSideRenderingEngineApplicationUrl
      Value: "http://rendering:3000"
    - ID: "fc76919b-0d7c-4732-865d-2af795fb38a4"
      Hint: serverSideRenderingEngineEndpointUrl
      Value: "http://rendering:3000/api/editing/render"
