---
ID: "2fa0b334-311c-4f99-a950-ac3eac4f1116"
Parent: "8fb503df-d132-4fc1-a096-18c8b8f19873"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/PLAY/playwebsite/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
