---
ID: "016a0a40-4ccb-47a9-83b9-8dabb97ef2f2"
Parent: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Template: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Path: /sitecore/templates/Project/PLAY/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
