---
ID: "28609a9b-97ad-425f-80cd-c4092a75c86a"
Parent: "742d06b0-3e34-4e15-bbac-fa2623268d96"
Template: "742d06b0-3e34-4e15-bbac-fa2623268d96"
Path: /sitecore/templates/Project/PLAY/Rendering Parameters/PLAY Styling and Grid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0b3aae91-ce72-4f5f-aead-4e5daad82506"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nko@sitecore.net
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221004T131522Z
