---
ID: "99a561e7-f0a2-55e2-a62b-ea13bae4ec23"
Parent: "675a1839-6fe8-59a6-a1e4-6ccbdbf2e966"
Template: "675a1839-6fe8-59a6-a1e4-6ccbdbf2e966"
Path: /sitecore/templates/Project/PLAY/Legacy/ThreeColumnsSection/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T133240Z
