---
ID: "9b5e1e18-fd8d-5e80-8028-861d007dca15"
Parent: "d0fcb3e6-7509-4ed4-a304-e0cc89f29c77"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/Project/PLAY/Products/ProductCategoriesGrid
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: ProductCategoriesGrid
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "edgeicons/32x32/icon-grid-large.png"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Project/Global/ProductCategoriesGrid
- ID: "a77e8568-1ab3-44f1-a664-b7c37ec7810d"
  Hint: Parameters Template
  Value: "{3C13BF6C-32DD-4F40-BCC9-208B47F21BB5}"
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: /sitecore/content/PLAY/playwebsite/Data/ProductCategoriesGrid
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50e56993-cbde-4259-bcd9-537df4d2c85a"
