---
ID: "84bc675b-55ea-5afb-bb03-aeaeee28544b"
Parent: "6cd0bc83-418d-5a02-9c04-0ba14235cd8b"
Template: "6cd0bc83-418d-5a02-9c04-0ba14235cd8b"
Path: /sitecore/templates/Project/PLAY/Legacy/TestimonyList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T133240Z
