---
ID: "a988761c-2447-57b7-b0cd-5c72294a9460"
Parent: "fdf43aad-c5d1-54e4-9909-59bfddc86689"
Template: "fdf43aad-c5d1-54e4-9909-59bfddc86689"
Path: /sitecore/templates/Project/PLAY/Legacy/FeaturedSpeakers/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T133240Z
