---
ID: "5a825ceb-31d2-4889-9f12-53120dce4968"
Parent: "bfe54f03-2ca7-4f4f-867e-daef974bae4d"
Template: "bfe54f03-2ca7-4f4f-867e-daef974bae4d"
Path: /sitecore/templates/Project/PLAY/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T133240Z
