---
ID: "5a825ceb-31d2-4889-9f12-53120dce4968"
Parent: "bfe54f03-2ca7-4f4f-867e-daef974bae4d"
Template: "bfe54f03-2ca7-4f4f-867e-daef974bae4d"
Path: /sitecore/templates/Project/PLAY/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
