---
ID: "602c4dc5-5c4e-5e25-afa1-6df5b5359304"
Parent: "5954b01b-2adb-53d6-85ee-e8408d2cc2a4"
Template: "5954b01b-2adb-53d6-85ee-e8408d2cc2a4"
Path: /sitecore/templates/Project/PLAY/Legacy/FullImageSection/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221012T133240Z
